### ISSUE TITLE
Still active?

### ISSUE THREAD

**Issue by duncan-bayne** [petar/GoLLRB#14]
Hi, I'm looking to use this library for a production tool, and was wondering if it's still being actively maintained?

**Comment by HuKeping** [comment]
@duncan-bayne you can follow https://github.com/HuKeping/GoCache

**Comment by duncan-bayne** [comment]
@HuKeping thanks :smile:

**Comment by soul9** [comment]
https://github.com/biogo/store/tree/master/llrb

**Comment by duncan-bayne** [comment]
Closing due to age.
